# config.yaml
basic_auth:
  users:
    - username: admin
      password: $2a$12$TqGMcaBkdF1J0b2QWDuFwurZNTD3bYpd4EZsDH6H81lGnY8lL9Rvi
    - username: another_user
      password: nvjnsoejcnsoeknwnefowen
    - username: sang
      password: 123456

pagination:
  page_size: 10
  page_number: 1
